# Generated by Django 5.1.2 on 2024-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_editorial_created_by_editorial_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
