# Generated by Django 5.1.2 on 2024-12-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_libro_autores_alter_libro_idioma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nacionalidad',
            new_name='f_nac',
        ),
    ]
