# Generated by Django 5.1.2 on 2025-01-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_autor_fecha_nacimiento_autor_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_es',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
