# Generated by Django 5.1.2 on 2025-01-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_libro_descripcion_en_libro_descripcion_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='books.autor'),
        ),
    ]
