"""
Django settings for biblioteca project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# de donde me encuentro "__file__" me voy 2 niveles de directorio màs arriba ".parent.parent"
BASE_DIR = Path(__file__).resolve().parent.parent
# creo una variable para indicar donde guardo mis templates
TEMPLATES_DIR = BASE_DIR / "biblioteca" / "template"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xo64kgxbw3nk6d8wvgu6d4^!-*q2^hb27#w8b2wo-)(m=24pr_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'debug_toolbar',
    'django_extensions',
    'import_export',
    'rosetta',
    'modeltranslation',

    'books',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # asegurarse de que este antes de CSRF y despues de session
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "books.custom_middleware.TiempoDeProcesamientoMiddleware",
]

ROOT_URLCONF = 'biblioteca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR,],  # se coloca "," por que es una lista
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.i18n", # añadido para poder tener disponible LANGUAGE en las plantillas
                "biblioteca.current_processor.get_current_year_context_processor",
                "biblioteca.current_processor.get_statistic_books",
            ],
        },
    },
]

WSGI_APPLICATION = 'biblioteca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# # Cambiamos a base de datos msql

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'mydb',                      # Nombre de la base de datos
#         'USER': 'django_user_db',             # Usuario creado para la base de datos
#         'PASSWORD': 'django_user_pass',       # Contraseña del usuario
#         'HOST': '127.0.0.1',                  # Dirección IP del host (localhost o la IP de tu máquina)
#         'PORT': '3306',                       # Puerto por defecto de MySQL
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-ES' # idioma por defecto

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

PREFIX_DEFAULT_LANGUAGE = True # si quiero un prefijo para el idioma por defecto en la url

# definir las opciones de idioma disponible
LENGUAGES = [
    ('en','English'),
    ('es','Español'),
]

# definir la ruta donde se guardan los archivos de traducción

LOCALE_PATHS = [
    BASE_DIR /  'locale', # 'locale' sera la carpeta donde se guardan las traducciones
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en' # para usar model translation tenemso que decir el idioma por defecto en esta variable
MODELTRANSLATION_LANGUAGES = ('es', 'en') # idiomas para la traducción
MODELTRANSLATION_FALLBACK_LANGUAGES = ('es',) # si el modelo no tiene traduccion para el idoma seleccionado por defecto uso español
#MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'es' # esto es para el admin idioma por defecto

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

LANGUAGE_COOKIE_NAME = 'django.language' # este es el valor por defecto se puede personalizar